root: ./

structure:
    summary: SUMMARY.md

redirects:
    install-and-configure/install/etl-backup/etl-backup: install-and-configure/install/multi-cluster/federated-etl/federated-etl-backups-alerting.md
    hc/en-us: README.md
    aws-out-of-cluster.html: install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-cloud-integrations.md
    custom-prom: install-and-configure/advanced-configuration/custom-prom/custom-prom.md
    custom-prom.html: install-and-configure/advanced-configuration/custom-prom/custom-prom.md
    install: install-and-configure/install/install.md
    apis/apis-overview/cost-events-audit-api: apis/governance-apis/cost-events-audit-api.md
    getting-started: install-and-configure/install/getting-started.md
    kubecost-cloud/using-the-kubecost-cloud-ui: v/kubecost-cloud/using-kubecost-cloud/using-kubecost-cloud.md
    using-kubecost/getting-started/cloud-costs-explorer: using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer.md
    using-kubecost/getting-started/alerts: using-kubecost/navigating-the-kubecost-ui/alerts.md
    using-kubecost/getting-started/audits: using-kubecost/navigating-the-kubecost-ui/audits.md
    controller: install-and-configure/advanced-configuration/controller/cluster-controller.md
    gcp-out-of-cluster: install-and-configure/install/cloud-integration/gcp-out-of-cluster/README.md
    architecture/network-allocation: using-kubecost/navigating-the-kubecost-ui/cost-allocation/network-allocation.md
    using-kubecost/getting-started/saved-reports: using-kubecost/navigating-the-kubecost-ui/saved-reports/reports.md
    saved-reports: using-kubecost/navigating-the-kubecost-ui/saved-reports/reports.md
    using-kubecost/navigating-the-kubecost-ui/savings/auto-request-sizing/containerstats-pipeline: architecture/containerstats-pipeline.md
    install-and-configure/advanced-configuration/controller: install-and-configure/advanced-configuration/controller/cluster-controller.md
    api-abandoned-workloads: apis/apis-overview/api-abandoned-workloads.md
    alerts: using-kubecost/navigating-the-kubecost-ui/alerts.md
    cost-allocation: using-kubecost/navigating-the-kubecost-ui/cost-allocation/README.md
    multi-cluster: install-and-configure/install/multi-cluster/multi-cluster.md
    enterprise: install-and-configure/install/install.md
    gcp-out-of-cluster.html: install-and-configure/install/cloud-integration/gcp-out-of-cluster/README.md
    enterprise.html: architecture/opencost-product-comparison.md
    alerts.html: alerts.md
    assets: using-kubecost/navigating-the-kubecost-ui/assets.md
    troubleshoot-install: troubleshooting/troubleshoot-install.md
    env: install-and-configure/install/environment.md
    install-and-configure/install/custom-prom: install-and-configure/advanced-configuration/custom-prom/custom-prom.md
    install-and-configure/install/custom-prom/gcp-gmp-integration: install-and-configure/advanced-configuration/custom-prom/gcp-gmp-integration.md
    using-kubecost/getting-started/assets: using-kubecost/navigating-the-kubecost-ui/assets.md
    hc/en-us/articles/10015110616599: federated-etl.md
    hc/en-us/articles/10018767892119: user-management-oidc.md
    hc/en-us/articles/10066023188119: api-persistent-volume-right-sizing.md
    hc/en-us/articles/10071917787159: containerstats-pipeline.md
    hc/en-us/articles/10248765796375: openshift-kubecost-install.md
    hc/en-us/articles/10330083197975: continuous-request-sizing.md
    hc/en-us/articles/4407595912983: add-key.md
    hc/en-us/articles/4407595915543: allocation-api.md
    hc/en-us/articles/4407595916823: allocation.md
    hc/en-us/articles/4407595918231: annotations.md
    hc/en-us/articles/4407595919895: api-request-right-sizing.md
    hc/en-us/articles/4407595921431: app-memory.md
    hc/en-us/articles/4407595922711: architecture/architecture.md
    hc/en-us/articles/4407595924247: assets.md
    hc/en-us/articles/4407595925271: readme.md
    hc/en-us/articles/4407595926423: availability-tiers.md
    hc/en-us/articles/4407595928087: aws-cloud-integrations.md
    hc/en-us/articles/4407595933847: aws-service-account-thanos.md
    hc/en-us/articles/4407595934871: install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-config.md
    hc/en-us/articles/4407595936023: azure-out-of-cluster.md
    hc/en-us/articles/4407595937175: install.md
    hc/en-us/articles/4407595938327: controller.md
    hc/en-us/articles/4407595941015: custom-prom.md
    hc/en-us/articles/4407595942679: install-and-configure/install/multi-cluster/multi-cluster-diagnostics.md
    hc/en-us/articles/4407595946135: install-and-configure/install/multi-cluster/multi-cluster.md
    hc/en-us/articles/4407595947799: install-and-configure/install/getting-started.md
    hc/en-us/articles/4407595950359: index.md
    hc/en-us/articles/4407595952151: long-term-storage-aws.md
    hc/en-us/articles/4407595954327: long-term-storage-azure.md
    hc/en-us/articles/4407595964695: long-term-storage.md
    hc/en-us/articles/4407595968919: install-and-configure/install/cloud-integration/README.md
    hc/en-us/articles/4407595970711: install-and-configure/install/multi-cluster/multi-cluster.md
    hc/en-us/articles/4407595972119: namespace-contacts.md
    hc/en-us/articles/4407595973527: using-kubecost/navigating-the-kubecost-ui/cost-allocation/network-allocation.md
    hc/en-us/articles/4407595974679: open-source-deps.md
    hc/en-us/articles/4407595975959: partner-metrics.md
    hc/en-us/articles/4407595977879: using-kubecost/navigating-the-kubecost-ui/reports.md
    hc/en-us/articles/4407595978903: security.md
    hc/en-us/articles/4407595980311: spot-checklist.md
    hc/en-us/articles/4407595981591: storage.md
    hc/en-us/articles/4407595983127: support-channels.md
    hc/en-us/articles/4407595985047: user-management.md
    hc/en-us/articles/4407596808087: aws-marketplace-install.md
    hc/en-us/articles/4407596809111: aws-node-price-reconcilitation-methodology.md
    hc/en-us/articles/4407596810519: install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-cloud-integrations.md
    hc/en-us/articles/4407601795863: air-gapped.md
    hc/en-us/articles/4407601796759: using-kubecost/navigating-the-kubecost-ui/alerts.md
    hc/en-us/articles/4407601797911: api-abandoned-workloads.md
    hc/en-us/articles/4407601802391: apis.md
    hc/en-us/articles/4407601805975: bug-report.md
    hc/en-us/articles/4407601807383: cost-allocation.md
    hc/en-us/articles/4407601809175: install.md
    hc/en-us/articles/4407601810199: env.md
    hc/en-us/articles/4407601811095: install-and-configure/install/etl-backup/etl-backup.md
    hc/en-us/articles/4407601816087: gcp-out-of-cluster.md
    hc/en-us/articles/4407601817495: google-service-account-thanos.md
    hc/en-us/articles/4407601818391: helm-install-params.md
    hc/en-us/articles/4407601820055: ingress-examples.md
    hc/en-us/articles/4407601821207: install.md
    hc/en-us/articles/4407601822359: long-term-storage-gcp.md
    hc/en-us/articles/4407601824279: prometheus.md
    hc/en-us/articles/4407601825431: release-process.md
    hc/en-us/articles/4407601826839: spinnaker-custom-webhook.md
    hc/en-us/articles/4407601828247: staging.md
    hc/en-us/articles/4407601829655: thanos-upgrade.md
    hc/en-us/articles/4407601830679: troubleshoot-install.md
    hc/en-us/articles/4407604999447: markdown.md
    hc/en-us/articles/4407763013271: readme.md
    hc/en-us/articles/4408095797911: ksm-metrics.md
    hc/en-us/articles/4408175613719: install-and-configure/install/provider-installations/istio-rancher.md
    hc/en-us/articles/4409859798679: install-and-configure/advanced-configuration/custom-prom/aws-amp-integration/.md
    hc/en-us/articles/4412353032599: spot-cluster-sizing.md
    hc/en-us/articles/4412369153687: cloud-integration.md
    hc/en-us/articles/4413635957271: rafay.md
    hc/en-us/articles/4423256582551: secondary-clusters.md
    hc/en-us/articles/4425080011671: ports.md
    hc/en-us/articles/4425132038167: agent.md
    hc/en-us/articles/4425134686743: user-metrics.md
    hc/en-us/articles/4442565953943: code-contribution.md
    hc/en-us/articles/5699259004311: install-and-configure/advanced-configuration/custom-prom/grafana-cloud-integration.md
    hc/en-us/articles/5748367035159: cluster-health-score.md
    hc/en-us/articles/5843799319703: api-request-recommendation-apply.md
    hc/en-us/articles/5843816284823: guide-one-click-request-sizing.md
    hc/en-us/articles/5991192077079: advanced-reports.md
    hc/en-us/articles/6152374933655: windows.md
    hc/en-us/articles/6446286863383: resource-consumption.md
    hc/en-us/articles/6737508001687: custom-grafana.md
    hc/en-us/articles/6737520506519: v1-94-turndown-schedule-migration-guide.md
    hc/en-us/articles/7302571484823: audit-api.md
    hc/en-us/articles/7788112146711: install-on-plural.md
    hc/en-us/articles/7923409206167: filters-v2.md
    hc/en-us/articles/8135370079511: asset-diff.md
    hc/en-us/articles/8241029276567: openshift-kubecost-install.md
    hc/en-us/articles/8292513994903: opencost-product-comparison.md
    hc/en-us/articles/8428105779095: aws-eks-cost-monitoring.md
    hc/en-us/articles/8445296194711: outages.md
    hc/en-us/articles/8554606459671: assets-api.md
    hc/en-us/articles/9038721747223: high-availability.md
    hc/en-us/articles/9176161195799: api-request-right-sizing-v2.md
    hc/en-us/articles/9177037361175: context-switcher.md
    hc/en-us/articles/9505088647319: events.md
    hc/en-us/articles/9530812762135: gpu-allocation.md
    hc/en-us/articles/10015110616599-Federated-ETL: federated-etl.md
    hc/en-us/articles/10018767892119-User-Management-SSO-OIDC: user-management-oidc.md
    hc/en-us/articles/10066023188119-Persistent-Volume-Right-Sizing-API: api-persistent-volume-right-sizing.md
    hc/en-us/articles/10071917787159--ContainerStats-Pipeline: containerstats-pipeline.md
    hc/en-us/articles/10248765796375-Deploy-Kubecost-from-Red-Hat-Openshift-s-OperatorHub-: openshift-kubecost-install.md
    hc/en-us/articles/10330083197975-Continuous-Request-Right-Sizing-with-Kubecost-s-Kubescaler: continuous-request-sizing.md
    hc/en-us/articles/4407595912983-Add-Key: add-key.md
    hc/en-us/articles/4407595915543-Kubecost-APIs: allocation-api.md
    hc/en-us/articles/4407595916823-Allocation-API: allocation.md
    hc/en-us/articles/4407595918231-Enabling-Annotation-Emission: annotations.md
    hc/en-us/articles/4407595919895-Container-Request-Right-Sizing-API: api-request-right-sizing.md
    hc/en-us/articles/4407595921431-Kubecost-Memory-Usage: app-memory.md
    hc/en-us/articles/4407595922711-Kubecost-Core-Architecture-Overview: architecture/architecture.md
    hc/en-us/articles/4407595924247-Assets: assets.md
    hc/en-us/articles/4407595925271-Auditing: readme.md
    hc/en-us/articles/4407595926423-Availability-Tiers: availability-tiers.md
    hc/en-us/articles/4407595928087-AWS-Cloud-Integration: aws-cloud-integrations.md
    hc/en-us/articles/4407595933847-Creating-a-Thanos-IAM-policy: aws-service-account-thanos.md
    hc/en-us/articles/4407595934871-Azure-Config: install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-config.md
    hc/en-us/articles/4407595936023-Adding-Azure-Out-of-Cluster-Cluster-Costs-into-Kubecost: azure-out-of-cluster.md
    hc/en-us/articles/4407595937175-Kubecost-Business-Features: install.md
    hc/en-us/articles/4407595938327-Cluster-Controller: controller.md
    hc/en-us/articles/4407595941015-Custom-Prometheus: custom-prom.md
    hc/en-us/articles/4407595942679-Kubecost-Diagnostics: install-and-configure/install/multi-cluster/multi-cluster-diagnostics.md
    hc/en-us/articles/4407595946135-Federated-Clusters: install-and-configure/install/multi-cluster/multi-cluster.md
    hc/en-us/articles/4407595947799-Getting-Started: install-and-configure/install/getting-started.md
    hc/en-us/articles/4407595950359-Welcome: index.md
    hc/en-us/articles/4407595952151-AWS-Multi-Cluster-Storage-Configuration: long-term-storage-aws.md
    hc/en-us/articles/4407595954327-Azure-Long-Term-Storage: long-term-storage-azure.md
    hc/en-us/articles/4407595964695-Long-Term-Storage: long-term-storage.md
    hc/en-us/articles/4407595968919-Setting-Up-Cloud-Integrations: install-and-configure/install/cloud-integration/README.md
    hc/en-us/articles/4407595970711-Multi-cluster: install-and-configure/install/multi-cluster/multi-cluster.md
    hc/en-us/articles/4407595972119-Namespace-Contacts: namespace-contacts.md
    hc/en-us/articles/4407595973527-Network-Traffic-Cost-Allocation: using-kubecost/navigating-the-kubecost-ui/cost-allocation/network-allocation.md
    hc/en-us/articles/4407595974679-Open-Source: open-source-deps.md
    hc/en-us/articles/4407595975959-Standardizing-Kubernetes-cost-allocation: partner-metrics.md
    hc/en-us/articles/4407595977879-Saved-Reports: using-kubecost/navigating-the-kubecost-ui/reports.md
    hc/en-us/articles/4407595978903-Security: security.md
    hc/en-us/articles/4407595980311-Spot-Checklist: spot-checklist.md
    hc/en-us/articles/4407595981591-Cost-Analyzer-Persistent-Volume: storage.md
    hc/en-us/articles/4407595983127-Getting-Support: support-channels.md
    hc/en-us/articles/4407595985047-User-Management-SSO-SAML: user-management.md
    hc/en-us/articles/4407596808087-AWS-Marketplace-Install: aws-marketplace-install.md
    hc/en-us/articles/4407596809111-AWS-Node-Price-Reconciliation-Methodology: aws-node-price-reconcilitation-methodology.md
    hc/en-us/articles/4407596810519-AWS-Out-of-Cluster-: install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-cloud-integrations.md
    hc/en-us/articles/4407601795863-Installing-in-Air-gapped-Environments: air-gapped.md
    hc/en-us/articles/4407601796759-Alerts-Documentation: using-kubecost/navigating-the-kubecost-ui/alerts.md
    hc/en-us/articles/4407601797911-Abandoned-Workloads: api-abandoned-workloads.md
    hc/en-us/articles/4407601802391-APIs: apis.md
    hc/en-us/articles/4407601805975-Capture-a-Bug-Report: bug-report.md
    hc/en-us/articles/4407601807383-Kubernetes-Cost-Allocation: cost-allocation.md
    hc/en-us/articles/4407601809175-Kubecost-Enterprise-Features: install.md
    hc/en-us/articles/4407601810199-Environment: env.md
    hc/en-us/articles/4407601811095-ETL-Backup: install-and-configure/install/etl-backup/etl-backup.md
    hc/en-us/articles/4407601816087-GCP-Out-of-Cluster: gcp-out-of-cluster.md
    hc/en-us/articles/4407601817495-Creating-a-Google-Service-Account: google-service-account-thanos.md
    hc/en-us/articles/4407601818391-Helm-Parameters: helm-install-params.md
    hc/en-us/articles/4407601820055-Ingress-Examples: ingress-examples.md
    hc/en-us/articles/4407601821207-Installing-Kubecost: install.md
    hc/en-us/articles/4407601822359-GCP-Long-Term-Storage: long-term-storage-gcp.md
    hc/en-us/articles/4407601824279-Running-a-query-in-Kubecost-bundled-Prometheus: prometheus.md
    hc/en-us/articles/4407601825431-Kubecost-Release-Process: release-process.md
    hc/en-us/articles/4407601826839-Custom-Webhook-to-Create-a-Kubecost-stage-in-Spinnaker: spinnaker-custom-webhook.md
    hc/en-us/articles/4407601828247-Deploy-Kubecost-Staging-Builds: staging.md
    hc/en-us/articles/4407601829655-Thanos-Upgrade: thanos-upgrade.md
    hc/en-us/articles/4407601830679-Troubleshoot-Install: troubleshoot-install.md
    hc/en-us/articles/4407604999447-Contributing-and-Markdown-Style-Guide: markdown.md
    hc/en-us/articles/4407763013271-Kubecost-Documentation: readme.md
    hc/en-us/articles/4408095797911-Kube-State-Metrics-KSM-Emission: ksm-metrics.md
    hc/en-us/articles/4408175613719-Installation-Kubecost-with-Istio-Rancher-: install-and-configure/install/provider-installations/istio-rancher.md
    hc/en-us/articles/4409859798679-Amazon-Managed-Service-for-Prometheus: install-and-configure/advanced-configuration/custom-prom/aws-amp-integration.md
    hc/en-us/articles/4409859798679-amazon-managed-service-for-prometheus: install-and-configure/advanced-configuration/custom-prom/aws-amp-integration.md
    hc/en-us/articles/4412353032599-Spot-Cluster-Sizing: spot-cluster-sizing.md
    hc/en-us/articles/4412369153687-Cloud-Integrations: cloud-integration.md
    hc/en-us/articles/4413635957271-Installing-Kubecost-with-Rafay: rafay.md
    hc/en-us/articles/4423256582551-Kubecost-Secondary-Clusters: secondary-clusters.md
    hc/en-us/articles/4425080011671-Ports: ports.md
    hc/en-us/articles/4425132038167-Installing-Agent-for-Hosted-Kubecost-Alpha-: agent.md
    hc/en-us/articles/4425134686743-User-Metrics: user-metrics.md
    hc/en-us/articles/4442565953943-Getting-Started: code-contribution.md
    hc/en-us/articles/5699259004311-Grafana-Cloud-Integration-for-Kubecost: install-and-configure/advanced-configuration/custom-prom/grafana-cloud-integration.md
    hc/en-us/articles/5748367035159-Cluster-Health-Score-: cluster-health-score.md
    hc/en-us/articles/5843799319703-Container-Request-Recommendation-Apply-APIs: api-request-recommendation-apply.md
    hc/en-us/articles/5843816284823-Guide-1-click-request-sizing: guide-one-click-request-sizing.md
    hc/en-us/articles/5991192077079-Advanced-Reporting: advanced-reports.md
    hc/en-us/articles/6152374933655-Windows-Node-Support: windows.md
    hc/en-us/articles/6446286863383-Tuning-Resource-Consumption: resource-consumption.md
    hc/en-us/articles/6737508001687-Grafana-Configuration-Guide: custom-grafana.md
    hc/en-us/articles/6737520506519-v1-94-TurndownSchedule-migration-guide: v1-94-turndown-schedule-migration-guide.md
    hc/en-us/articles/7302571484823-Audit-API: audit-api.md
    hc/en-us/articles/7788112146711-Installing-Kubecost-with-Plural: install-on-plural.md
    hc/en-us/articles/7923409206167-V2-Filters: filters-v2.md
    hc/en-us/articles/8135370079511-Asset-Diff-API: asset-diff.md
    hc/en-us/articles/8241029276567-Install-Kubecost-on-Redhat-OpenShift-cluster: openshift-kubecost-install.md
    hc/en-us/articles/8292513994903-OpenCost-Product-Comparison: opencost-product-comparison.md
    hc/en-us/articles/8428105779095-Amazon-EKS-integration: aws-eks-cost-monitoring.md
    hc/en-us/articles/8445296194711-Outages: outages.md
    hc/en-us/articles/8554606459671-Assets-API: assets-api.md
    hc/en-us/articles/9038721747223-High-Availability-Kubecost: high-availability.md
    hc/en-us/articles/9176161195799-Container-Request-Right-Sizing-Recommendation-API-v2-: api-request-right-sizing-v2.md
    hc/en-us/articles/9177037361175-Contexts: context-switcher.md
    hc/en-us/articles/9505088647319-Events-API: events.md
    hc/en-us/articles/9530812762135--GPU-Allocation: gpu-allocation.md
