name: "Bug Report"
description: Report a bug in the Kubecost documentation.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please tell us about the bug.
  - type: input
    id: link
    attributes:
      label: Page link
      description: >-
        Please provide the page link where the bug can be found.
      # placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Describe the problem.
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: bug-expectations
    attributes:
      label: Expected behavior
      description: What would you like to see?
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: true
