name: "Enhancement"
description: Recommend an enhancement to the Kubecost documentation.
title: "[Enhancement] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        What would you like to see added to the documentation?
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what enhancement you'd like to see.
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: true
