apiVersion: v1
kind: Service
metadata:
  name: kubecost-frontend
  namespace: kubecost
  labels:
    app: cost-analyzer
spec:
  type: LoadBalancer
  ports:
    - port: 9090
  selector:
    app: cost-analyzer
